<?php

/**
 *
 */
// // DO NOT MODIFY THIS FILE... THIS FILE IS AUTOGENERATED FROM manifest.template.php during build_zip.sh script!
// DO NOT MODIFY THIS FILE... THIS FILE IS AUTOGENERATED FROM manifest.template.php during build_zip.sh script!
// DO NOT MODIFY THIS FILE... THIS FILE IS AUTOGENERATED FROM manifest.template.php during build_zip.sh script!
// DO NOT MODIFY THIS FILE... THIS FILE IS AUTOGENERATED FROM manifest.template.php during build_zip.sh script!
// DO NOT MODIFY THIS FILE... THIS FILE IS AUTOGENERATED FROM manifest.template.php during build_zip.sh script!
// DO NOT MODIFY THIS FILE... THIS FILE IS AUTOGENERATED FROM manifest.template.php during build_zip.sh script!


$manifest = [
    'acceptable_sugar_versions' => [
        'exact_matches' =>
        [
            '6.4.0',
        ],
        'regex_matches' =>
        [
            '6\.4\.\d',
            '6\.[0-5]\.\d', /** matches 6.1.x,6.2.x,6.3.x,6.4.x,6.5.x * */
        ],
    ],
    'acceptable_sugar_flavors' => [
        'CE'
        , 'PRO'
        , 'ENT'
    ],
    'readme' => 'Модуль расширения отчётов',
    'key' => '',
    'author' => 'Алексей Дубровский / ООО "КУБ ТРИ" ',
    'description' => '',
    'icon' => '',
    'is_uninstallable' => true,
    'name' => 'Extends SuiteCRM AOR_Reports',
    'published_date' => '2022-Sep-07 08:09',
    'type' => 'module',
    'version' => '2.0.1.1-SNAPSHOT',
    'remove_tables' => 'prompt',
];

$installdefs = [
    'id' => 'Extends_SuiteCRM_AOR_Reports',
    'copy' => [
        [
            'from' => '<basepath>/SugarModules/custom/',
            'to' => 'custom/',
        ],
        [
            'from' => '<basepath>/README.md',
            'to' => 'custom/modules/AOR_Reports/README.md',
        ],
        [
            'from' => '<basepath>/CHANGELOG.md',
            'to' => 'custom/modules/AOR_Reports/CHANGELOG.md',
        ],
    ],
];
